# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calsync < Formula
  desc "Sync a local calendar to a remote Google Calendar"
  homepage "http://github.com/shadyabhi/calsync"
  version "0.1.19"

  on_macos do
    url "https://github.com/shadyabhi/calsync/releases/download/v0.1.19/calsync_Darwin_all.tar.gz"
    sha256 "920557100bcceb899820b80ea9965864b954217caacaa13b24da5a2b873b7ed6"

    def install
      bin.install "calsync"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/calsync/releases/download/v0.1.19/calsync_Linux_x86_64.tar.gz"
      sha256 "4b6d817221d4f1a011436830c191259048c2557475101076490c33131683741f"
      def install
        bin.install "calsync"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/calsync/releases/download/v0.1.19/calsync_Linux_arm64.tar.gz"
      sha256 "1c799b8b8267e6f1c0720c0b2cfb7aab06331073301190a2649146f1273b763f"
      def install
        bin.install "calsync"
      end
    end
  end

  def caveats
    <<~EOS
      For install instructions, visit: https://github.com/shadyabhi/calsync/wiki
    EOS
  end
end
