# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calsync < Formula
  desc "Sync a local calendar to a remote Google Calendar"
  homepage "http://github.com/shadyabhi/calsync"
  version "0.0.38"

  depends_on "ical-buddy"

  on_macos do
    url "https://github.com/shadyabhi/calsync/releases/download/v0.0.38/calsync_Darwin_all.tar.gz"
    sha256 "ded72479433ffd656ea0c9ad4f41e146ad0c83423534694c3dbe41e4583e8dc1"

    def install
      bin.install "calsync"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/calsync/releases/download/v0.0.38/calsync_Linux_arm64.tar.gz"
      sha256 "1e0018a0a236a5603cd76d63afc4f1c7883c70cf6c2d10a4099999d36706c32a"

      def install
        bin.install "calsync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shadyabhi/calsync/releases/download/v0.0.38/calsync_Linux_x86_64.tar.gz"
      sha256 "d7527fcc4e7b7259d0217b6e63715135c95952166ef7f667a271935c88e09a40"

      def install
        bin.install "calsync"
      end
    end
  end

  service do
    run [opt_bin/"calsync"]
    run_type :interval
    interval 300
    log_path "/usr/local/var/log/calsync.out.log"
    error_log_path "/usr/local/var/log/calsync.err.log"
    working_dir HOMEBREW_PREFIX
  end
end
