# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantee < Formula
  desc "A TUI for reading man pages"
  homepage "https://github.com/shadyabhi/mantee"
  version "0.0.2"

  on_macos do
    url "https://github.com/shadyabhi/mantee/releases/download/v0.0.2/mantee_Darwin_all.tar.gz"
    sha256 "c8857895cb402e73b08ee5c17c19cf1e9fb5d3d0dcbc416c40b7af3ae63f4875"

    def install
      bin.install "mantee"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/mantee/releases/download/v0.0.2/mantee_Linux_x86_64.tar.gz"
      sha256 "0f6ed3fa7ae581c7617d776fba3809722a610548c500184cfb5ec5f775835166"
      def install
        bin.install "mantee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/mantee/releases/download/v0.0.2/mantee_Linux_arm64.tar.gz"
      sha256 "3e2a70888c8383b7fad1ee2e75d04d3ac8f70f44a691d1771b953a2091fe22ac"
      def install
        bin.install "mantee"
      end
    end
  end
end
