# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantee < Formula
  desc "A TUI for reading man pages"
  homepage "https://github.com/shadyabhi/mantee"
  version "0.0.3"

  on_macos do
    url "https://github.com/shadyabhi/mantee/releases/download/v0.0.3/mantee_Darwin_all.tar.gz"
    sha256 "7d0fd2aebfdb63dbd401075e4f4525a6df284164e22848cf00520e1c5e97e51a"

    def install
      bin.install "mantee"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/mantee/releases/download/v0.0.3/mantee_Linux_x86_64.tar.gz"
      sha256 "dbba8ad77e3800377d9bb79d47be3b8ce73d0b1d73b1fc2d5a0392d3deb9c238"
      def install
        bin.install "mantee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shadyabhi/mantee/releases/download/v0.0.3/mantee_Linux_arm64.tar.gz"
      sha256 "ea3a44724cc2e89f0ec252f2389d98eea2f667f7b6f1c42ca12722d739a4371a"
      def install
        bin.install "mantee"
      end
    end
  end
end
